#+TITLE: Interia
#+LANGUAGE: es

Motor de Historias Interactivas, hecho en Lua y Love2D para la feria de ciencias INNOVA 2021

* Como funciona
Interia carga las historias desde una carpeta en específico:

=/home/usuario/.local/share/Interia/stories= en Linux

=C:\Documents and Settings\usuario\Application Data\Interia\stories= en Windows XP

=C:\Users\usuario\AppData\Roaming\Interia\stories= en Windows Vista, 7, 8 y 10

=/Users/usuario/Library/Application Support/Interia/stories= en Mac

Nótese que se reemplaza =usuario= con el nombre del usuario que esté actualmente usando la aplicación

También carga la [[Configuración][configuración]] en:

=/home/usuario/.local/share/Interia/config/conf.lua= en Linux

=C:\Documents and Settings\usuario\Application Data\Interia\config\conf.lua= en Windows XP

=C:\Users\usuario\AppData\Roaming\Interia\config\conf.lua= en Windows Vista, 7, 8 y 10

=/Users/usuario/Library/Application Support/Interia/config/conf.lua= en Mac

En este también se reemplaza =usuario= con el nombre de usuario que usa la aplicación

Luego las lee e interpreta cada párrafo, sección, línea y letra siguiendo un conjunto de [[Reglas][reglas]] y las transforma en un conjunto de elementos que la computadora puede entender

Este conjunto se separa en [[Secciones][secciones]] y se muestra cada una según corresponda

* Instalación
** Linux
Descargar e instalar [[https://love2d.org][Love2D]], posiblemente también esté en su gestor de paquetes.

Descargar el archivo *Interia.love* desde la página de [[https://github.com/Bowuigi/Interia/releases][releases]]

El commando para abrir Interia es =love --fused "/lugar/de/interia.love"=

Este se puede poner en un *script* o en un *archivo .desktop* para poder abrirlo desde el menú de aplicaciones
** Windows
Descargar el archivo *Interia-Win.zip* desde la página de [[https://github.com/Bowuigi/Interia/releases][releases]].

Extraer el archivo zip (Click derecho > =Extraer en Interia-Win/=).

Entrar a la carpeta *Interia-Win* recién creada.

Dar doble click al archivo *Interia.exe*.

Si se desea, se puede arrastrar el mismo archivo a la barra de tareas o al escritorio para no tener que navegar a la carpeta cada vez que desee lanzar la herramienta.
** MacOS
Descargar el archivo *Interia-OSX.zip* desde la página de [[https://github.com/Bowuigi/Interia/releases][releases]]

Extraer el mismo en una carpeta

Verificar que *interia.app* sea ejecutable

Ejecutarlo

* Post instalación
Poner las [[Historias][historias]] obtenidas en el [[Como funciona][lugar correspondiente]].

Cambiar la [[Configuración][configuración]] a gusto.

* Historias
Son un archivo de texto plano (no son documentos de Word ni PDF), generalmente tienen las extensiones *.his* o *.txt* y pueden ser creadas y editadas por distintos editores de texto, como:

+ Linux
  * El por defecto de su entorno de escritorio (generalmente llamado "editor de texto")
  * Cualquier editor de terminal (nvim, micro, nano, ne, etc.)
+ Windows
  * Block de notas
+ MacOS
  * TextEdit (En la pestaña "Formato", seleccione "Crear texto sin formato")
  * Cualquier editor de terminal (nvim, nano, ne, micro, etc.)

Cuando se selecciona *editar* en una historia dentro de Interia, se abre el mismo archivo en el editor de texto predeterminado.

Para crear una nueva historia, abra Interia, presione *abrir la carpeta de historias*, crear un archivo de *texto plano* en esa ubicación, y escriba la historia según las [[Reglas][reglas]]
* Reglas
** Secciones
Las historias de Interia se separan por secciones, estas se crean de la siguiente manera

#+begin_src text
seccion:
	El texto va aquí
	Otra línea de texto
#+end_src

Esto crea una sección llamada *seccion* que contiene dos lineas de texto

Nótese que hay una sangría en cada línea perteneciente a la sección recién declarada, esta sangría es de solo un carácter y se consigue con un espacio o una tabulación (que se consigue apretando tab, que es la tecla con dos flechas apuntando a lados opuestos)

Esta sangría es obligatoria y se usa para diferenciar el contenido de las secciones de la declaración de las mismas, esta misma sangría no se ve en la aplicación.

Solo la primera sección se mostrará en la aplicación, esto se puede cambiar con links (vínculos), que se explican más abajo.

Relevante: [[Acerca de los nombres de las secciones]]

** Contenido
Cada sección puede o no tener contenido. Como se agrega el contenido está explicado más arriba, pero sería algo como:

#+begin_src text
nombre_de_seccion:
	Este texto es parte del contenido
	La cantidad de contenido que puede tener una sección no tiene límites, además de la memoria y el tamaño del texto
	Se puede mover hacia ambos lados para ver el texto completo si la línea es muy larga
#+end_src

Esto crea una sección llamada *nombre_de_seccion* que en Interia se ve de la siguiente manera:

#+begin_src text
Este texto es parte del contenido
La cantidad de contenido que puede tener una sección no tiene límites, además de la memoria y el tamaño del texto
Se puede mover hacia ambos lados para ver el texto completo si la línea es muy larga
#+end_src

** Títulos
Los títulos son una parte importante de las historias, y también en Interia.

Los títulos se definen de la siguiente manera:

#+begin_src text
capitulo_1:
	#Capítulo 1, la pared
	Texto de ejemplo
#+end_src

Si se prueba en la aplicación, se verá que la línea con el =#= se ve resaltada, pero el =#= mismo no se muestra, esto significa que es un título.

Un título puede ir en cualquier parte de una sección. Así como una sección puede no contener títulos.

** Links (vínculos)
El link es una forma de cambiar la sección visible por una con un nombre en específico. Si esa sección no está disponible, se toma como un link a una página web y se abre en el navegador.

El link se declara de la siguiente forma:

#+begin_src text
capitulo_1:
	@capitulo_2
	Texto que se muestra en lugar de "@capitulo_2"

capitulo_2:
	Hola!
	@capitulo_1
	Click aqui para ir al capítulo anterior
#+end_src

Si se prueba esto desde la aplicación, se ve solo el contenido del primer capítulo, que es un link al segundo, en lugar de verse =@capitulo_2= se ve el texto que está debajo.

Si se le da click, te lleva a la sección con el nombre luego del *@*, en este caso =capitulo_2=, mostrando el contenido de ese capítulo.

Si en lugar de el nombre de una sección se utiliza un hipervínculo, como "https://gnu.org", abrirá el navegador para mostrar la página correspondiente.

Esto permite que Interia se pueda extender con páginas que permitan usar imágenes, videos, presentaciones y otros.

Relevante: [[Acerca de los links (vínculos)]]
** Acerca de los nombres de las secciones
Los nombres de las secciones no pueden contener:

+ Espacios.

+ Caracteres fuera de la tabla ASCII (como í,ó,→,etc.), esto es por un tema de codificación.

+ Líneas nuevas (lo que aparece cuando se presiona enter).

+ El nombre *sections*; esto es por un tema interno, si una sección se llama de esa manera se reemplazara, posiblemente resultando en problemas.

** Acerca de los links (vínculos)
No hay límites en la cantidad de links que se pueden poner.

Los links a archivos se pueden crear usando =file://= y luego la dirección del archivo.

No se recomienda el uso de estos porque la ubicación de las cosas cambia según el sistema operativo (por ejemplo, las direcciones en Windows llevan =\\=, y en Linux y MacOS llevan =/=, por lo que resultaría en un error o no dependiendo de donde se abre)

* Configuración
La misma se ubica en la carpeta de configuración de Interia, cerca de la carpeta de historias, reemplazando =stories= por =config=

Específicamente en el archivo *conf.lua* de la misma carpeta.

** Por defecto
#+begin_src lua
-- Configuración de Interia, el motor de historias interactivas
keys= {
	--   Normales | Vi
	up=   {"up",   "k"},
	down= {"down", "j"},
	left= {"left", "h"},
	right={"right","l"},
}
scrollspeed=15

-- Traducción
nostoriesstr="No hay ninguna historia en %s\nAgrega una para que aparezca aquí!" -- Necesita %s en donde iría la carpeta
storiesdirstr="Las historias van en %s" -- Necesita %s en donde iría la carpeta
storyselstr={
	sel="Elegiste:",
	nosel="Elige tu historia:",
}
menustr={
	read="Leer",
	edit="Editar",
	cancel="Cancelar",
}

exitstr="Salir"
folderstr="Abrir la carpeta de historias"

-- Los colores son de 0 a 1
-- Y son en formato R,G,B
theme= {
	background = {
		0,0,0
	},
	panelcolors = {
		0.2,0.2,0.2
	},
	textcolors = {
		normal = {bg={0,0,0},fg={1,1,1}}
	},
	buttoncolors = {
		normal  = {bg={0,0,0,0},fg={0,0.3,1}},
		hovered = {bg={0,0,0,0},fg={1,1,1}},
		active  = {bg={0,0,0,0},fg={1,1,1}},
	},
	exitbuttoncolors = {
			normal  = {bg={0,0.1,1},fg={1,1,1}},
			hovered = {bg={0,0.7,0.2},fg={1,1,1}},
			active  = {bg={0,0.3,1},fg={1,1,1}},
	}
}
#+end_src

** Descripción
*** Teclas
#+begin_src lua
keys= {
	--   Normales | Vi
	up=   {"up",   "k"},
	down= {"down", "j"},
	left= {"left", "h"},
	right={"right","l"},
}
scrollspeed=15
#+end_src

Acá se cambian cuales teclas de el teclado se usan para hacer distintas cosas, además de la velocidad a la que se mueve la pantalla.

La lista *keys* contiene todas las acciones que se pueden realizar en el teclado en Interia, las cuales son:

| Variable | Acción                     | Por defecto    |
|----------+----------------------------+----------------|
| up       | Moverse hacia arriba       | {"up",    "k"} |
| down     | Moverse hacia abajo        | {"down",  "j"} |
| left     | Moverse hacia la izquierda | {"left",  "h"} |
| right    | Moverse hacia la derecha   | {"right", "l"} |

Se pueden añadir más opciones cambiando la parte por defecto por algo como lo siguiente:

#+begin_src lua
keys= {
	--   Normales | Vi | Extras recien añadidas
	up=   {"up",   "k", "w"},
	down= {"down", "j", "s"},
	left= {"left", "h", "a"},
	right={"right","l", "d"},
}
scrollspeed=15
#+end_src

=scrollspeed= es una variable que define la velocidad a la que se mueve la pantalla, es *15* por defecto.

*** Traducción
#+begin_src lua
-- Traducción
nostoriesstr="No hay ninguna historia en %s\nAgrega una para que aparezca aquí!" -- Necesita %s en donde iría la carpeta
storiesdirstr="Las historias van en %s" -- Necesita %s en donde iría la carpeta
storyselstr={
	sel="Elegiste:",
	nosel="Elige tu historia:",
}
menustr={
	read="Leer",
	edit="Editar",
	cancel="Cancelar",
}

exitstr="Salir"
folderstr="Abrir la carpeta de historias"
#+end_src

Esta sección corresponde al texto que contiene Interia, se puede cambiar simplemente reemplazando el texto que está entre comillas, aquí un ejemplo, conteniendo una traducción en inglés:

#+begin_src lua
-- Traducción
nostoriesstr="There is no stories in %s\nAdd one so it can appear here!" -- Necesita %s en donde iría la carpeta
storiesdirstr="Stories go in %s" -- Necesita %s en donde iría la carpeta
storyselstr={
	sel="You chose:",
	nosel="Select a story:",
}
menustr={
	read="Read",
	edit="Edit",
	cancel="Cancel",
}

exitstr="Exit"
folderstr="Open the stories folder"
#+end_src

*** Tema (colores)
#+begin_src lua
-- Los colores son de 0 a 1
-- Y son en formato R,G,B
theme= {
	background = {
		0,0,0
	},
	panelcolors = {
		0.2,0.2,0.2
	},
	textcolors = {
		normal = {bg={0,0,0},fg={1,1,1}}
	},
	buttoncolors = {
		normal  = {bg={0,0,0,0},fg={0,0.3,1}},
		hovered = {bg={0,0,0,0},fg={1,1,1}},
		active  = {bg={0,0,0,0},fg={1,1,1}},
	},
	exitbuttoncolors = {
			normal  = {bg={0,0.1,1},fg={1,1,1}},
			hovered = {bg={0,0.7,0.2},fg={1,1,1}},
			active  = {bg={0,0.3,1},fg={1,1,1}},
	}
}
#+end_src

| Variable         | Significado                                                                                    |
|------------------+------------------------------------------------------------------------------------------------|
| background       | Color de fondo (RGB)                                                                           |
| panelcolors      | Colores del menú que aparece al dar click a una historia (RGBA)                                |
| textcolors       | Color del texto en general (bg=fondo (RGB), fg=texto (RGB))                                    |
| buttoncolors     | Color de casi todos los botones en estados activo, con el mouse encima y normal (RGB cada uno) |
| exitbuttoncolors | Lo mismo pero solo para el botón de salir de la historia                                       |
